### PR TITLE
Feat/linting formatting Fe

### PR DESCRIPTION
**Pull request by nikolas-rauscher**
## Description

* 

## Related Backlog Item

Issue: #88 

You can now run

````
make lint
make format
````
from FE and root.

---

### Context

* 

---

## Checklist:
- [x] I have documented my changes
- [x] I have tested the changes and they work as expected
- [x] I have assigned this PR to someone
- [x] I have run `make format` to format my code

### CODE REVIEW

**Review by Sandeep-kumar-Ramesh — COMMENTED** [review]
Formatting works fine. I am attaching the screenshot for linting. When I changed some alignment and ran "make lint", I expected to see some lint errors. But instead, I got some error with prettier plugin. Can you kindly check this.
image

**Comment by nikolas-rauscher** [comment]
@Sandeep-kumar-Ramesh  can you look at it again?

**Comment by Sandeep-kumar-Ramesh** [comment]
> @Sandeep-kumar-Ramesh can you look at it again?

Yes sure, I will look into it again

**Comment by Sandeep-kumar-Ramesh** [comment]
Now everything looks good to me

**Review by Sandeep-kumar-Ramesh — APPROVED** [review]
Everything looks good to me

**Pull request merged**
